# Generated by Django 5.0.3 on 2024-03-14 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_alter_appointment_user'),
        ('doctors', '0002_doctoradvice'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoradvice',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
            preserve_default=False,
        ),
    ]
