# Generated by Django 5.0.2 on 2024-02-28 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(choices=[('Dr. Smith', 'Dr. Smith'), ('Dr. Johnson', 'Dr. Johnson'), ('Dr. Williams', 'Dr. Williams'), ('Dr. Brown', 'Dr. Brown')], max_length=100)),
                ('time', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM')], max_length=5)),
                ('date', models.DateField()),
                ('appointment_option', models.CharField(choices=[('video_call', 'Video Call'), ('offline_meeting', 'Offline Meeting')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
